# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_cpp <- function(x, y) {
    .Call(`_rpkgcpp_add_cpp`, x, y)
}

#' Sum along a vector
#'
#' Returns the sum of a vector, x, of real numbers.
#' @param x A vector of real/double numbers
#' @export
sumC <- function(x) {
    .Call(`_rpkgcpp_sumC`, x)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_rpkgcpp_RcppExport_registerCCallable`)
})
